schema_version = 1
name = "ENERGY STAR 4.8 cu. ft. top-load washer with Sanitize with Oxi and FlexDispense"
brand = "GE Appliances"
manufacturer = "GE Appliances, a Haier company"
model = "GTW720BSNWS"
product_url = "https://www.geappliances.com/appliance/GE-ENERGY-STAR-4-8-cu-ft-Capacity-Washer-with-Sanitize-w-Oxi-and-FlexDispense-GTW720BSNWS"
support_url = "https://products.geappliances.com/appliance/gea-specs/GTW720BSNWS/support"
