schema_version = 1
name = "Standard Duty Pneumatic Door Closer, White"
brand = "Wright Products"
manufacturer = "Hampton Products International Corporation"
model = "US920WH"
product_url = "https://www.wrightproducts.com/products/standard-duty-pneumatic-closer/v920wh"
