schema_version = 1
name = "EcoTank ET-3850 wireless all-in-one Supertank printer"
brand = "Epson"
manufacturer = "Seiko Epson Corporation"
model = "ET-3850"
product_url = "https://epson.com/For-Work/Printers/Inkjet/EcoTank-ET-3850-Wireless-Color-All-in-One-Cartridge-Free-Supertank-Printer-with-ADF%2C-Duplex-Printing-and-Large-Paper-Tray/p/C11CJ61201"
support_url = "https://epson.com/Support/Printers/All-In-Ones/ET-Series/Epson-ET-3850/s/SPT_C11CJ61201"
